export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_TRANSFERS = 'UPDATE_TRANSFERS';
export const UPDATE_HOME = 'UPDATE_HOME';
export const ADD_HOME_TO_USER = 'ADD_HOME_TO_USER';
export const REMOVE_HOME_FROM_USER = 'REMOVE_HOME_FROM_USER';
